### ISSUE TITLE
Update README.md to explain --reload

### ISSUE THREAD

**Issue by ddarbyson** [panthomakos/guard-yard#12]
You should consider updating the usage example implying cli option `--reload`, otherwise writing docs on the fly doesn't reparse the library code on each request.

**README.md**

```
guard 'yard', :port => '8808', :cli => '--reload' do
  ...
end
```

Thanks for the guard plugin!

**Comment by panthomakos** [comment]
Somehow this issue slipped through the cracks. I'm very sorry about that. The `--reload` option should not be necessary because `guard` + `guard-yard` will monitor files and reload the server. Please re-open the issue if you can provide some more details or a sample project in which this is not the case.

Thank you!
