### ISSUE TITLE
yard server is not killed on Windows

### ISSUE THREAD

**Issue by agross** [panthomakos/guard-yard#21]
SIGQUIT is not supported on Windows:

```
15:15:05 - ERROR - Guard::Yard failed to achieve its <stop>, exception was:
> [#ec503285559f] ArgumentError: unsupported name `SIGQUIT'
> [#ec503285559f] C:/Ruby/lib/ruby/gems/2.2.0/gems/guard-yard-2.1.4/lib/guard/yard/server.rb:30:in `kill'
> [#ec503285559f] C:/Ruby/lib/ruby/gems/2.2.0/gems/guard-yard-2.1.4/lib/guard/yard/server.rb:30:in `kill'
> [#ec503285559f] C:/Ruby/lib/ruby/gems/2.2.0/gems/guard-yard-2.1.4/lib/guard/yard.rb:22:in `stop'
```

One solution might be to catch the ArgumentError in Windows and then run `taskkill /f` with the PID.

http://blog.simplificator.com/2016/01/18/how-to-kill-processes-on-windows-using-ruby/

**Comment by panthomakos** [comment]
@agross I would be happy to look at a Pull Request that deals with properly killing the server on Windows. I cannot personally work on Windows support because I don't ever use the OS and cannot test in that environment.  If you would like to take a stab at this I would recommend using `Gem.win_platform?` to determine if you are on Windows and then using the appropriate signal/command to kill the process.
